<h1>Python - Arithmetic Operators & Evaluating Expressions</h1>
<hr style="height:2px;border:none;color:#333;background-color:#333;" />
<p>This lesson covers the following topics:
<ul>
    <li><a href="#arithmetic">Arithmetic Operators</a></li>
    <li><a href="#mixing">Mixing Data Types</a></li>
    <li><a href="#evaluate">Evaluating Expressions</a></li>
</ul>
</p>

<hr>
<a id="arithmetic"></a>
<h3>Arithmetic Operators</h3>
<p style="text-align:justify;">
    <a href="https://www.w3schools.com/python/gloss_python_arithmetic_operators.asp">Arithmetic operators</a> are used with numeric values to perform common mathematical operations:
</p>

<table style="float:left;font-size:16px;text-align:left;">
  <tr style="background-color:#c5dfed">
    <th style="font-size:16px;text-align:left;">Operator</th>
    <th style="font-size:16px;text-align:left;">Name</th>
    <th style="font-size:16px;text-align:left;">Example</th>
  </tr>
  <tr>
    <td style="font-size:16px;text-align:left;">+</td>
    <td style="font-size:16px;text-align:left;">Addition</td>
    <td style="font-size:16px;text-align:left;">x + y</td>
  </tr>
  <tr>
    <td style="font-size:16px;text-align:left;">-</td>
    <td style="font-size:16px;text-align:left;">Subtraction</td>
    <td style="font-size:16px;text-align:left;">x - y</td>
  </tr>
  <tr>
    <td style="font-size:16px;text-align:left;">*</td>
    <td style="font-size:16px;text-align:left;">Multiplication</td>
    <td style="font-size:16px;text-align:left;">x * y</td>
  </tr>
  <tr>
    <td style="font-size:16px;text-align:left;">/</td>
    <td style="font-size:16px;text-align:left;">True Division</td>
    <td style="font-size:16px;text-align:left;">x / y</td>
  </tr>
  <tr>
    <td style="font-size:16px;text-align:left;">//</td>
    <td style="font-size:16px;text-align:left;">Integer Division</td>
    <td style="font-size:16px;text-align:left;">x // y</td>
  </tr>
  <tr>
    <td style="font-size:16px;text-align:left;">%</td>
    <td style="font-size:16px;text-align:left;">Modulus Division</td>
    <td style="font-size:16px;text-align:left;">x % y</td>
  </tr>
  <tr>
    <td style="font-size:16px;text-align:left;">**</td>
    <td style="font-size:16px;text-align:left;">Exponentiation</td>
    <td style="font-size:16px;text-align:left;">x ** y</td>
  </tr>
</table>

<table style="float:right;font-size:16px;text-align:left;">
  <tr style="background-color:#c5dfed">
    <th style="font-size:16px;text-align:left;">Operator</th>
    <th style="font-size:16px;text-align:left;">Assignment (long-hand)</th>
    <th style="font-size:16px;text-align:left;">Assignment (short-hand)</th>
  </tr>
  <tr>
    <td style="font-size:16px;text-align:left;">+</td>
    <td style="font-size:16px;text-align:left;">x = x + y</td>
    <td style="font-size:16px;text-align:left;">x += y</td>
  </tr>
  <tr>
    <td style="font-size:16px;text-align:left;">-</td>
    <td style="font-size:16px;text-align:left;">x = x - y</td>
    <td style="font-size:16px;text-align:left;">x -= y</td>
  </tr>
  <tr>
    <td style="font-size:16px;text-align:left;">*</td>
    <td style="font-size:16px;text-align:left;">x = x * y</td>
    <td style="font-size:16px;text-align:left;">x *= y</td>
  </tr>
  <tr>
    <td style="font-size:16px;text-align:left;">/</td>
    <td style="font-size:16px;text-align:left;">x = x / y</td>
    <td style="font-size:16px;text-align:left;">x /= y</td>
  </tr>
  <tr>
    <td style="font-size:16px;text-align:left;">//</td>
    <td style="font-size:16px;text-align:left;">x = x // y</td>
    <td style="font-size:16px;text-align:left;">x //= y</td>
  </tr>
  <tr>
    <td style="font-size:16px;text-align:left;">%</td>
    <td style="font-size:16px;text-align:left;">x = x % y</td>
    <td style="font-size:16px;text-align:left;">x %= y</td>
  </tr>
  <tr>
    <td style="font-size:16px;text-align:left;">**</td>
    <td style="font-size:16px;text-align:left;">x = x ** y</td>
    <td style="font-size:16px;text-align:left;">x **= y</td>
  </tr>
</table>

In [1]:
# Here are some examples of using arithmetic operators.
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
print("23 + 7 =", 23 + 7)
print("23 - 7 =", 23 - 7)
print("23 * 7 =", 23 * 7)
print("23 / 7 =", 23 / 7)
print("23 // 7 =", 23 // 7)
print("23 % 7 =", 23 % 7)
print("23 ** 7 =", 23 ** 7)

# Here are some examples of arithmetic operators used with an assignment.
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
x = 55
x = x + 34         # equivalent to x += 34
x = x - 21         # equivalent to x -= 21
x = x * 13         # equivalent to x *= 13
x = x / 8          # equivalent to x /= 8
x = x // 5         # equivalent to x //= 5
x = x % 3          # equivalent to x %= 3

23 + 7 = 30
23 - 7 = 16
23 * 7 = 161
23 / 7 = 3.2857142857142856
23 // 7 = 3
23 % 7 = 2
23 ** 7 = 3404825447

<hr>
<a id="mixing"></a>
<h3>Mixing Data Types</h3>
<p style="text-align:justify;">
Python has many built-in <a href="https://www.w3schools.com/python/python_datatypes.asp">data types</a> and we need to know what happens when we mix different data types while using arithmetic operators. The rule of thumb while mixing data types is, <u>the larger data type always wins</u>.
</p>
<p>
    Here are some of the data-types of interest from largeset to smallest:
<ol>
    <li>String (largest)</li>
    <li>Float</li>
    <li>Integer (smallest)</li>
</ol>

In [2]:
# Here are some legal examples of mixing data-types with arithmetic operators.

print('1 + 2.0 =', 1 + 2.0)     # Integer + Float => Float
print('3 * "2" =', 3 * "2")     # Integer * String => String


# We can always mix numeric data types, but there are limitations while mixing other data types.
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# For exemple, we can't:
# - Add Strings and Numbers
# - Subtract Strings and Numbers
# - Divide Strings and Numbers

1 + 2.0 = 3.0
3 * "2" = 222

<hr>
<a id="evaluate"></a>
<h3>Evaluating Expressions</h3>
<p style="text-align:justify;">
While evaluating expressions in code, the typical mathematical heirarchy rules apply (PEMDAS).<br /><br />
However, we have to keep two additional things in mind:
<ol>
    <li>Each operation's respective data types will dictate the resulting data type.</li>
    <li>The interpreter is going to read from left to right, unless otherwise dictated.</li>
</ol>
</p>

<table style="float:left;font-size:14px;text-align:left;">
  <tr style="background-color:#c5dfed">
    <th style="font-size:14px;text-align:left;">Precedence</th>
    <th style="font-size:14px;text-align:left;">Operator(s)</th>
    <th style="font-size:14px;text-align:left;">Description</th>
  </tr>
  <tr>
    <td style="font-size:14px;text-align:left;">Highest</td>
    <td style="font-size:14px;text-align:left;">( )</td>
    <td style="font-size:14px;text-align:left;">Parenthesis</td>
  </tr>
  <tr>
    <td style="font-size:14px;text-align:left;"></td>
    <td style="font-size:14px;text-align:left;">**</td>
    <td style="font-size:14px;text-align:left;">Exponentiation</td>
  </tr>
  <tr>
    <td style="font-size:14px;text-align:left;"></td>
    <td style="font-size:14px;text-align:left;">*</td>
    <td style="font-size:14px;text-align:left;">Multiplication</td>
  </tr>
  <tr>
    <td style="font-size:14px;text-align:left;"></td>
    <td style="font-size:14px;text-align:left;">/  //  %</td>
    <td style="font-size:14px;text-align:left;">Division (True, Integer, Modulus)</td>
  </tr>
  <tr>
    <td style="font-size:14px;text-align:left;"></td>
    <td style="font-size:14px;text-align:left;">+</td>
    <td style="font-size:14px;text-align:left;">Addition</td>
  </tr>
  <tr>
    <td style="font-size:14px;text-align:left;">Lowest</td>
    <td style="font-size:14px;text-align:left;">-</td>
    <td style="font-size:14px;text-align:left;">Subtraction</td>
  </tr>
</table>

<br />
$
\begin{align*}
\text{Example 1.)}\qquad4\;*\;3\;//\;8\;&+\;2.5\;*\;2 & \qquad\qquad
\text{Example 2.)}\qquad89\;\%\;10\;/\;4*2.0\;/\;5&+(1.5+1.0\;/\;2)*2\\\\
\underbrace{4\;*\;3}_{12}//\;8\;&+\;\underbrace{2.5\;*\;2}_{5.0} & 
\underbrace{89\;\%\;10}_{9}\;/\;4*2.0\;/\;5&+\underbrace{(1.5+1.0\;/\;2)}_{1.5\;+\;0.5}*2\\\\
\underbrace{12\;//\;8}_{1}\;&+\;5.0 & \underbrace{9\;/\;4}_{2.25}*2.0\;/\;5&+(\underbrace{1.5+0.5}_{2.0})*2\\\\
1\;&+\;5.0 & \underbrace{2.25*2.0}_{4.5}\;/\;5&+\underbrace{2.0*2}_{4.0}\\\\
&\fbox{6.0} & \underbrace{4.5\;/\;5}_{0.9}&+4.0\\\\
&&0.9&+4.0\\\\
&&&\fbox{4.9}
\end{align*}
$